apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-persistent-storage
          persistentVolumeClaim:
            claimName: nginx-pv-claim
      containers:
      - name: nginx
        image: hsaadaou/nginx
        imagePullPolicy: Never
        livenessProbe:
          periodSeconds: 3
          initialDelaySeconds: 10
          exec:
            command:
            - /bin/ash
            - /livenessprobe.sh
        volumeMounts:
          - name: nginx-persistent-storage
            mountPath: /home/
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: SSH_USER
            valueFrom:
              secretKeyRef:
                key: SSH_USER
                name: sshsecret
          - name: SSH_PASSWORD
            valueFrom:
              secretKeyRef:
                key: SSH_PASSWORD
                name: sshsecret
          - name: FTP_USER
            valueFrom:
              secretKeyRef:
                key: FTP_USER
                name: ftpssecret
          - name: FTP_PASSWORD
            valueFrom:
              secretKeyRef:
                key: FTP_PASSWORD
                name: ftpssecret
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_ROOT_PASSWORD
                name: mysqlsecret
          - name: ADMIN_WP_USER
            valueFrom:
              secretKeyRef:
                key: ADMIN_WP_USER
                name: mysqlsecret
          - name: ADMIN_WP_PASS
            valueFrom:
              secretKeyRef:
                key: ADMIN_WP_PASS
                name: mysqlsecret
          - name: USER1_WP_USER
            valueFrom:
              secretKeyRef:
                key: USER1_WP_USER
                name: mysqlsecret
          - name: USER1_WP_PASS
            valueFrom:
              secretKeyRef:
                key: USER1_WP_PASS
                name: mysqlsecret
          - name: USER2_WP_USER
            valueFrom:
              secretKeyRef:
                key: USER2_WP_USER
                name: mysqlsecret
          - name: USER2_WP_PASS
            valueFrom:
              secretKeyRef:
                key: USER2_WP_PASS
                name: mysqlsecret
