apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: hsaadaou/wordpress
        imagePullPolicy: Never
        livenessProbe:
          periodSeconds: 3
          initialDelaySeconds: 15
          exec:
            command:
            - /bin/ash
            - /livenessprobe.sh
        env:
          - name: WP_DB_NAME
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: WP_DB_NAME
          - name: ADMIN_WP_USER
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: ADMIN_WP_USER
          - name: ADMIN_WP_PASS
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: ADMIN_WP_PASS
          - name: USER1_WP_USER
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: USER1_WP_USER
          - name: USER1_WP_PASS
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: USER1_WP_PASS
          - name: USER2_WP_USER
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: USER2_WP_USER
          - name: USER2_WP_PASS
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: USER2_WP_PASS
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
          - containerPort: 5050
